name: CI/CD for Spring Boot API with Docker

on:
  push:
    branches:
      - dev  # Trigger workflow only on pushes to the dev branch
  pull_request:
    branches:
      - dev  # Trigger workflow for pull requests to dev branch

jobs:
  # Job 1: Build and Test Backend
  build_and_test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('cds-backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -D skipTests
        working-directory: cds-backend  # Ensure Maven runs in the backend directory

  # Job 2: Docker Build, Push to Docker Hub, and Deploy
  docker_build_and_deploy:
    needs: build_and_test_backend
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          # Build the Docker images using Docker Compose
          docker compose -f cds-backend/docker-compose.yml build
          
          # Debug: List built images
          docker images
          
          docker tag cds-backend:latest sree27/cds-backend:latest

          # Push the Docker image to Docker Hub
          docker push sree27/cds-backend:latest


